import localFont from 'next/font/local';
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const poppins = localFont({
	src: [
		{
			path: '../assets/fonts/poppins/Poppins-Regular.ttf',
			weight: '400',
			style: 'normal'
		},
	],
	variable: '--font-poppins'
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} font-poppins`}>
				{children}
			</body>
		</html>
	);
}
