export const BASE_ERROR_CODES = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    FAILED_TO_CREATE_USER: 'FAILED_TO_CREATE_USER',
    FAILED_TO_UPDATE_USER: 'FAILED_TO_UPDATE_USER',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
};
