const DASHBOARD_PREFIX = 'dashboard';

const RESOURCE_GROUPS = {
    EVENTS: 'EVENTS',
    PAYMENTS: 'PAYMENTS',
    PLATFORM_SETTINGS: 'PLATFORM_SETTINGS',
};

const RESOURCE_GROUP_MAP: Record<string, string> = {
    events: RESOURCE_GROUPS.EVENTS,
    eventTypes: RESOURCE_GROUPS.EVENTS,
    tickets: RESOURCE_GROUPS.PAYMENTS,
    settings: RESOURCE_GROUPS.PLATFORM_SETTINGS,
    reservations: RESOURCE_GROUPS.EVENTS,
};

export {DASHBOARD_PREFIX, RESOURCE_GROUPS, RESOURCE_GROUP_MAP};
